# Generated by rust2rpm
%bcond_with check
%global debug_package %{nil}

%global crate tokio-async-await

Name:           rust-%{crate}
Version:        0.1.7
Release:        3%{?dist}
Summary:        Experimental async/await support for Tokio

License:        MIT
URL:            https://crates.io/crates/tokio-async-await
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(futures/default) >= 0.1.23 with crate(futures/default) < 0.2.0)
BuildRequires:  (crate(tokio-io/default) >= 0.1.7 with crate(tokio-io/default) < 0.2.0)
%if %{with check}
BuildRequires:  (crate(bytes/default) >= 0.4.9 with crate(bytes/default) < 0.5.0)
BuildRequires:  (crate(hyper/default) >= 0.12.8 with crate(hyper/default) < 0.13.0)
BuildRequires:  (crate(tokio/default) >= 0.1.8 with crate(tokio/default) < 0.2.0)
%endif

%global _description \
Experimental async/await support for Tokio.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+async-await-preview-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-await-preview-devel %{_description}

This package contains library source intended for building other packages
which use "async-await-preview" feature of "%{crate}" crate.

%files       -n %{name}+async-await-preview-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.7-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.7-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Apr 23 15:25:05 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.7-1
- Initial package
